services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    restart: always

  nginx:
    image: nginx:1.28.0-alpine
    volumes:
      - ./nginx_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
